name: My App

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: welcome  message
          run: |
            echo "Badal Singh"
            ls -lart
            cat README.md

        # - name: List Files
        #   run: ls

        # - name: Read Files
        #   run: cat README.md
