name: My App

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: welcome  message
          run: |
            
            mkdir -p badal
            echo "Badal Singh" > badal/kur.txt

        - uses: actions/upload-artifact@v3
          with:
            name: artficat
            path: badal/kur.txt
    
    upload_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: welcome  message
          run: |
            
            mkdir -p badal
            echo "Badal Singh" > badal/kur.txt

        - uses: actions/download-artifact@v3
          with:
            name: artficat
        
